version: '3.8'

services:
  wireshark:
    image: tulia311/wireshark
    container_name: wireshark
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
    ports:
      - "2222:22"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
