version: "3.8"

services:
  wireshark:
    image: wireshark
    container_name: wireshark_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: host
    command: bash -c "/etc/init.d/ssh start && tail -f /dev/null"
    restart: unless-stopped
    